/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import java.time.LocalDateTime;


public class App {
    public String getGreeting() {

        return "Hello World!";

    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
        System.out.println("Timestamp = " + LocalDateTime.now());

    }
}
