pipeline {
    agent any

    

    stages {
        stage('Clone Repository') {
            steps {
                // Checkout your repo's main branch
                git branch: 'main', url: 'https://github.com/Sabeshragav/jenkins-java-1'
            }
        }

        stage('Build with Gradle') {
            steps {
                // Clean and build the Gradle project, fail build on error
                bat 'gradlew clean build'
            }
        }

        // stage('Archive Artifact') {
        //     steps {
        //         // Archive any jar file(s) generated inside the target directory
        //         archiveArtifacts artifacts: 'target/*.jar', fingerprint: true
        //     }
        // }

        stage('Executing jar file') {
            steps {
                // Execute the jar file generated by Gradle
                bat 'java -cp app/build/libs/App.jar org.example.App' 
            }
        }
    }

    post {
        success {
            echo 'Build and archive completed successfully!'
        }
        failure {
            echo 'Build failed! Check console output for errors.'
        }
    }
}